# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NYU Skullhouse | Phi Kappa Sigma Fraternity | Delta Phi Chapter | New York University
email: omega@skullhouse.nyc
description: > # this means to ignore newlines until "baseurl:"
  Skullhouse is New York University’s premier society for men who seek
  intellectual stimulation, lifelong friendships, and a network of passionate
  individuals who share common values.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  PhiKappaSigma

# Build settings
markdown: kramdown
